[workspace]
authors = ["Julius Busecke <johndoe@example.com>"]
channels = ["conda-forge"]
name = "rtma"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[dependencies]
jupyterlab = ">=4.5.2,<5"
xarray = ">=2025.12.0,<2026"
cfgrib = ">=0.9.15.1,<0.10"
coiled = ">=1.130.3"
jupyter-server-proxy = ">=4.4.0"
arraylake = ">=0.28.1,<0.29"
obstore = ">=0.8.2,<0.9"
boto3 = ">=1.42.35,<2"
matplotlib = ">=3.10.8,<4"

[tasks]
coiled-notebook = "coiled notebook start --sync --region us-east-1 --memory 32GB"
coiled-notebook-ooompph = "coiled notebook start --sync --region us-east-1 --cpu 64 --memory 256GB"
